CREATE TABLE IF NOT EXISTS `admin` (
    `admin_id`         INTEGER  PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(150) NOT NULL,
    `password` VARCHAR(70) NOT NULL
);

CREATE TABLE IF NOT EXISTS `user` (
   `user_id`         INTEGER  PRIMARY KEY AUTO_INCREMENT,
   `username` VARCHAR(150) NOT NULL,
   `email` VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS `token` (
  `token_id`  INTEGER PRIMARY KEY AUTO_INCREMENT,
  `token` VARCHAR(250) NOT NULL,
  `is_logged_out` INT(1) NOT NULL DEFAULT 0,
  `admin_id` INTEGER NOT NULL
)
